In [ ]:
#to convert boolean value to int datatype==>dummies = dummies.astype(int)
#drop one col from table df_final=  dummies.drop('Car Model_BMW X5', axis=1) OR final.drop(['west windsor'], axis='columns')
#NOTE  if there is spce betwwen word then take df_final['Sell Price($)'] instead of df_final.Sell Price($)
# Predict price of a mercedez benz that is 4 yr old with mileage 45000==>model.predict([[45000,4,0,1]])

In [51]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [52]:
import pandas as pd

# Specify the path to your CSV file
file_path = r'R:\ML\ML nd Dl by codebasics\csv\carprices_encoding.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [16]:
print("Column names:", df.columns)

Column names: Index(['Car Model', 'Mileage', 'Sell Price($)', 'Age(yrs)'], dtype='object')


In [54]:
dummies = pd.get_dummies(df, columns=['Car Model'])
dummies = dummies.astype(int)
dummies

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  Car Model_BMW X5  \
0     69000          18000         6                  0                 1   
1     35000          34000         3                  0                 1   
2     57000          26100         5                  0                 1   
3     22500          40000         2                  0                 1   
4     46000          31500         4                  0                 1   
5     59000          29400         5                  1                 0   
6     52000          32000         5                  1                 0   
7     72000          19300         6                  1                 0   
8     91000          12000         8                  1                 0   
9     67000          22000         6                  0                 0   
10    83000          20000         7                  0                 0   
11    79000          21000         7                  0                 0   
12    59000          33000         5                  0                 0   

    Car Model_Mercedez Benz C class  
0                                 0  
1                                 0  
2                                 0  
3                                 0  
4                                 0  
5                                 0  
6                                 0  
7                                 0  
8                                 0  
9                                 1  
10                                1  
11                                1  
12                                1

In [6]:
print("Column names:", dummies.columns)

Column names: Index(['Mileage', 'Sell Price($)', 'Age(yrs)', 'Car Model_Audi A5',
       'Car Model_BMW X5', 'Car Model_Mercedez Benz C class'],
      dtype='object')


In [55]:
df_final=  dummies.drop('Car Model_BMW X5', axis=1)

In [56]:
df_final

Mileage  Sell Price($)  Age(yrs)  Car Model_Audi A5  \
0     69000          18000         6                  0   
1     35000          34000         3                  0   
2     57000          26100         5                  0   
3     22500          40000         2                  0   
4     46000          31500         4                  0   
5     59000          29400         5                  1   
6     52000          32000         5                  1   
7     72000          19300         6                  1   
8     91000          12000         8                  1   
9     67000          22000         6                  0   
10    83000          20000         7                  0   
11    79000          21000         7                  0   
12    59000          33000         5                  0   

    Car Model_Mercedez Benz C class  
0                                 0  
1                                 0  
2                                 0  
3                                 0  
4                                 0  
5                                 0  
6                                 0  
7                                 0  
8                                 0  
9                                 1  
10                                1  
11                                1  
12                                1

In [57]:
X = df_final.drop('Sell Price($)', axis='columns')
X

Mileage  Age(yrs)  Car Model_Audi A5  Car Model_Mercedez Benz C class
0     69000         6                  0                                0
1     35000         3                  0                                0
2     57000         5                  0                                0
3     22500         2                  0                                0
4     46000         4                  0                                0
5     59000         5                  1                                0
6     52000         5                  1                                0
7     72000         6                  1                                0
8     91000         8                  1                                0
9     67000         6                  0                                1
10    83000         7                  0                                1
11    79000         7                  0                                1
12    59000         5                  0                                1

In [61]:
y = df_final['Sell Price($)'] #NOTE  if there is spce betwwen word then take df_final['Sell Price($)'] instead of df_final.Sell Price($)
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int32

In [62]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [63]:
model.fit(X,y)
model.predict(X) # 2600 sqr ft home in new jersey

array([18705.27236456, 35286.78445595, 24479.1911246 , 41245.76426317,
       29882.98779028, 28023.61352427, 30614.46818485, 21879.57266985,
       12182.34562162, 26183.72387896, 18929.31674144, 20409.80511892,
       30477.15426153])

In [64]:
model.predict([[45000,4,0,1]]) # Predict price of a mercedez benz that is 4 yr old with mileage 45000

C:\Users\rakes\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36991.31721031])

In [ ]:
model.predict([[86000,7,0,0]]) # Predict price of a BMW X5 that is 7 yr old with mileage 86000

In [25]:
model.score(X,y)

0.9417050937281082

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [29]:
dfle = df
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [30]:
X =  dfle.drop('Sell Price($)', axis=1).to_numpy()  # Convert to 2D NumPy array
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]], dtype=int64)

In [31]:
y = dfle['Sell Price($)'].values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000], dtype=int64)

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder = 'passthrough')

In [33]:
X = ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [49]:
X = X[:,1:]
X

InvalidIndexError: (slice(None, None, None), slice(1, None, None))

In [35]:
model.fit(X,y)

LinearRegression()

In [37]:
model.predict([[1,46000,31500,4]]) # 3400 sqr ft home in west windsor

array([1.12898124e+08])