In [1]:
import pandas as pd

# 1D array
array_1d = [1, 2, 3, 4, 5]

# Convert to 2D DataFrame and then to a 2D array
array_2d = pd.DataFrame(array_1d).values
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
# 1D array
array_1d = [1, 2, 3, 4, 5]

# Convert to 2D array with one column
array_2d = [[x] for x in array_1d]
print(array_2d)

[[1], [2], [3], [4], [5]]


In [3]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = np.expand_dims(array_1d, axis=1)
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = array_1d[:, np.newaxis]
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = array_1d.reshape(-1, 1)
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
# Specify the path to your CSV file
file_path = r'R:\ML\ML nd Dl by codebasics\csv\salaries.csv'

# Load the CSV file into a DataFrame
df= pd.read_csv(file_path)
new_df=df
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:
# Create a mapping from the factorize method
mapping, _ = pd.factorize(new_df['company'])
print(mapping)
# Convert 'company' to numeric in a single line using apply and the previously created mapping
new_df['company'] = new_df['company'].apply(lambda x: mapping[new_df['company'].tolist().index(x)])

print(new_df)

[0 0 0 0 0 0 1 1 1 1 2 2 2 2 2 2]
    company                  job     degree  salary_more_then_100k
0         0      sales executive  bachelors                      0
1         0      sales executive    masters                      0
2         0     business manager  bachelors                      1
3         0     business manager    masters                      1
4         0  computer programmer  bachelors                      0
5         0  computer programmer    masters                      1
6         1      sales executive    masters                      0
7         1  computer programmer  bachelors                      0
8         1     business manager  bachelors                      0
9         1     business manager    masters                      1
10        2      sales executive  bachelors                      1
11        2      sales executive    masters                      1
12        2     business manager  bachelors                      1
13        2     business man