In [1]:
import pandas as pd

# 1D array
array_1d = [1, 2, 3, 4, 5]

# Convert to 2D DataFrame and then to a 2D array
array_2d = pd.DataFrame(array_1d).values
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [2]:
# 1D array
array_1d = [1, 2, 3, 4, 5]

# Convert to 2D array with one column
array_2d = [[x] for x in array_1d]
print(array_2d)

[[1], [2], [3], [4], [5]]


In [3]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = np.expand_dims(array_1d, axis=1)
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [4]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = array_1d[:, np.newaxis]
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with one column
array_2d = array_1d.reshape(-1, 1)
print(array_2d)

[[1]
 [2]
 [3]
 [4]
 [5]]
